Repository openedx/wg-build-test-release, pull requests merged in 2021-04, with the labels that each got.

#48 Automatically add new issues to Project
  .github/workflows/add-issue-to-project.yml
Labels: type:btr-task

#26 docs: add issue tracking process
  docs/decisions/0004-issue-tracking.rst
Labels: affects:koa, type:btr-task, type:documentation

#25 docs: Add release timeline ADR
  docs/decisions/0003-release-timeline.rst
Labels: priority:high, type:btr-task, type:documentation

#13 Base ADRs, role definitions, and assignments
  README.rst
  docs/decisions/0001-github-repository-and-issues.rst
  docs/decisions/0002-role-definitions.rst
Labels: type:documentation, type:enhancement
